###Security UI
###Security login
POST http://localhost:3000/login/security
Content-Type: application/json

{
    "username":"HARITH",
    "password":"123456"
}
###security register user account
POST http://localhost:3000/register/user 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhBUklUSCIsImlhdCI6MTcwMzc3MTcxOCwiZXhwIjoxNzAzNzcyMzE4fQ.EQGYzIy-D-jS3lB0VVeQ6rgffyJDemMlo4WMuJyTbyo

{
    "username":"ANEP",
    "password":"123456",
    "name":"HARIH ROSLY",
    "email":"harithrosly@mail.com"
}
###security view all the visitor data
GET http://localhost:3000/view/visitor/security
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhBUklUSCIsImlhdCI6MTcwMzc3MzA5MCwiZXhwIjoxNzAzNzczNjkwfQ.R1WWlQHt3k-FZcCTCq8lbyMRg0vNqFE4wDzBJJrRpgY

### User UI
###User login 
POST http://localhost:3000/login/user
Content-Type: application/json

{
    "username":"ANEP",
    "password":"123456"
}
###User create visitor 
POST http://localhost:3000/create/visitor/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFORVAiLCJpYXQiOjE3MDM2NDA2NDgsImV4cCI6MTcwMzY0MTI0OH0.SqEr4q9LqlDyzH235LGKxUpFxzpPeflEDXAI7zq17Jo
{
    "visitorname": "AMIR",
    "checkintime": "2001-06-24T09:34:55Z",
    "checkouttime":"2001-06-24T13:23:50Z",    
    "temperature":"27.5",
    "gender":"male",
    "ethnicity":"buddha",
    "age":"22",
    "phonenumber":"013247547"
}
###user view all visitors data that had created by that him (login user)
GET http://localhost:3000/view/visitor/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNBTSIsImlhdCI6MTcwMzUwMDYxOSwiZXhwIjoxNzAzNTAwNjc5fQ.s5NTsjdIQ1fJvJYrTAp9qMjc8MIdVuwODCXSbY7Ailw

###User update their visitor info
PUT http://localhost:3000/update/visitor/Celine
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNBTSIsImlhdCI6MTY4NjkyMjU4OSwiZXhwIjoxNjg2OTIyNjQ5fQ.nAJXns8tTq4JvJYtroU-4LtE3_D-iH-Qda5MmgvXiPM

{
    "checkintime": "2002-06-23T06:30:55Z",
    "checkouttime":"2002-06-27T06:50:50Z",    
    "temperature":"26.9",
    "gender":"female",
    "ethnicity":"Kirstian",
    "age":"26",
    "phonenumber":"012345678"
}

### Visitor UI
###Visitor view their data
GET http://localhost:3000/view/visitor/JOHN
